version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR.....
      - aws --version
      #- apt install docker.io
      #- aws ecr get-login --no-include-email --region us-east -1
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/v8p9f0s1
      
  
  build:
    commands:
      - echo Build started on `date`
      - docker build -t nodejsapp .
      - docker tag nodejsapp:latest public.ecr.aws/v8p9f0s1/nodejsapp:latest

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push public.ecr.aws/v8p9f0s1/nodejsapp:latest
