version: 0.2
 
  install:
  pre_build:
    commands:
     - Logging in to Amazon ECR.....
     - apt install awscli
    - $(aws ecr get-login --no-include-email --region us-east-1)
    - REPOSITORY_URI=public.ecr.aws/v8p9f0s1/nodejsapp:latest

  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t public.ecr.aws/v8p9f0s1/nodejsapp:latest .
    
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker images...
    - docker push custom-03.dkr.ecr.us-east-1.amazonaws.com/nodejsapp:latest
    - echo Writing image definitions file...
