version: 0.2
phases:
  pre_build:
    commands:
      #- $(aws ecr get-login --no-include-email --region us-east-1)
      - REPOSITORY_URI=public.ecr.aws/v8p9f0s1/node
      - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/v8p9f0s1
  build:
    commands:
      - "echo Build started on `date`"
      - "echo Building the Docker image..."
      - docker build -t node .
      #- docker tag node:latest public.ecr.aws/v8p9f0s1/node:latest
  post_build:
    commands:
      - "echo Build completed on `date`"
      - "echo Pushing the Docker image..."
      - docker push public.ecr.aws/v8p9f0s1/node:latest
      - printf '[{"name":"node","imageUri":"%s"}]' 318451290319.dkr.ecr.us-east-1.amazonaws.com/assign > imagedefinitions.json
      - cat imagedefinitions.json
artifacts:
    files: imagedefinitions.json
