version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region us-east-1 --no-include-email)
      - REPOSITORY_URI=public.ecr.aws/v8p9f0s1/nodejsapp:latest
      #- aws ecr-public get-login-password  --region us-east-1  | docker login --username AWS --password-stdin public.ecr.aws/v8p9f0s1
     
  build:
    commands:
      - echo Build started on `date`
      - echo building the docker images...
      - docker build -t  115717770171.dkr.ecr.us-east-1.amazonaws.com/node .
      
     
  post_build:
    commands:
      - echo Build completed on `date`
      #- docker tag ok 115717770171.dkr.ecr.us-east-1.amazonaws.com/node
      - docker push 115717770171.dkr.ecr.us-east-1.amazonaws.com/node
     
      
artifacts:
  files:
    - '**/*'
