version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      #- REPOSITORY_URI=public.ecr.aws/v8p9f0s1/nodejsapp:latest
     
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t public.ecr.aws/v8p9f0s1/nodejsapp:latest .
     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push public.ecr.aws/v8p9f0s1/nodejsapp:latest
     
      
artifacts:
  files:
    - '**/*'
